import re

html_file = "tw/materiality_analysis.html"
with open(html_file, "r", encoding="utf-8") as f:
    content = f.read()

start_idx = content.find('id="text-env-aspect"')
svg_start = content.rfind('<svg', 0, start_idx)
svg_end = content.find('</svg>', start_idx)
svg_content = content[svg_start:svg_end]

# Remove all <rect ... fill="transparent" ...> or just any <rect> injected inside <a>
# We know inject_svg.py injected: <rect x="..." y="..." width="..." height="..." fill="transparent"></rect>
# Let's just remove `<rect[^>]*fill="transparent"[^>]*>` or `</rect>` from inside a_tags
def clean_a_tag(match):
    a_content = match.group(0)
    # Remove the rect
    a_content = re.sub(r'<rect[^>]*fill="transparent"[^>]*></rect>', '', a_content)
    a_content = re.sub(r'<rect[^>]*fill="transparent"[^>]*>.*?</rect>', '', a_content)
    a_content = re.sub(r'<rect[^>]*fill="transparent"[^>]*/>', '', a_content)
    return a_content

new_svg_content = re.sub(r'<a[^>]*>.*?</a\s*>', clean_a_tag, svg_content, flags=re.DOTALL)

# Also wait, the rects generated by inject_svg.py were:
# ET.Element('{http://www.w3.org/2000/svg}rect', x=..., y=..., width=..., height=..., fill="transparent")
# Because it's ElementTree, it might be <rect fill="transparent" height="..." width="..." x="..." y="..." />

new_content = content[:svg_start] + new_svg_content + content[svg_end:]

with open(html_file, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Removed all transparent rects from a tags!")
